name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3  # Update to the latest version

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Update to the latest version
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 44.218.204.229 >> ~/.ssh/known_hosts

      - name: Rsync deployments
        run: |
          rsync -avzr --delete --exclude=".git" ./* ubuntu@44.218.204.229:/var/www/my-app/

      - name: Restart PM2 process
        run: |
          ssh ubuntu@44.218.204.229 << 'EOF'
            cd /var/www/my-app/
            pm2 kill
            pm2 start /var/www/my-app/app.js --name "my-app" --watch
          EOF
