name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ SSH_PRIVATE_KEY.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 44.218.204.229 >> ~/.ssh/known_hosts

      - name: rsync deployments
        run: |
          rsync -avzr --delete ./* ubuntu@44.218.204.229:/var/www/my-app/

      - run: npm run start
